[book]
authors = ["Humberto Ortiz-Zuazaga"]
language = "es"
multilingual = false
src = "src"
title = "Diseño de Compiladores"
[output.html]
theme = "src/theme"
#additional-js = ["mermaid.min.js"]
[preprocessor.mermaid]
command = "mdbook-mermaid"
